name: Lint and Rebuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Lint code with ruff
        run: |
          ruff .

      - name: Trigger Render deploy if main.py changed
        if: contains(github.event.head_commit.message, 'main.py') || contains(join(github.event.commits.*.modified, ','), 'main.py')
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
